# Generated by Django 3.0.8 on 2021-02-22 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acessoDados', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dados',
        ),
        migrations.DeleteModel(
            name='ListaBens',
        ),
        migrations.DeleteModel(
            name='ListaDividas',
        ),
    ]
