# Generated by Django 3.0.8 on 2021-02-22 01:32

import acessoDados.validations
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acessoDados', '0002_auto_20210221_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaBens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(default='', max_length=50)),
                ('data_aquisicao', models.DateField(default=datetime.date.today)),
                ('valor_aquisicao', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tipo', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ListaDividas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(default='', max_length=50)),
                ('valor_divida_original', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_divida_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tipo_divida', models.CharField(default='', max_length=20)),
                ('numero_contrato', models.IntegerField(default=0)),
                ('data_divida', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, validators=[acessoDados.validations.validate_CPF])),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=80)),
                ('idade', models.IntegerField(default=0)),
                ('fonte_renda', models.CharField(max_length=50)),
                ('id_lista_dividas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acessoDados.ListaDividas')),
                ('lista_bens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acessoDados.ListaBens')),
            ],
        ),
    ]
