# Generated by Django 3.0.8 on 2021-02-22 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acessoDados', '0003_dados_listabens_listadividas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados',
            name='id_lista_dividas',
        ),
        migrations.RemoveField(
            model_name='dados',
            name='lista_bens',
        ),
    ]
