# Generated by Django 3.0.8 on 2021-02-22 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessoDados', '0004_auto_20210221_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='created_date',
            field=models.DateTimeField(auto_created=True, default=datetime.date.today, editable=False),
        ),
        migrations.AddField(
            model_name='dados',
            name='updated_date',
            field=models.DateTimeField(auto_created=True, default=datetime.date.today),
        ),
    ]
