# Generated by Django 3.0.8 on 2021-02-22 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acessoDados', '0005_auto_20210221_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='created_date',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='dados',
            name='updated_date',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='listabens',
            name='data_aquisicao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='listadividas',
            name='data_divida',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
