# Generated by Django 3.0.8 on 2021-02-23 02:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acessoDados', '0009_auto_20210222_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosBens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('descricao', models.CharField(default='', max_length=50)),
                ('data_aquisicao', models.DateField(default=django.utils.timezone.now)),
                ('valor_aquisicao', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tipo', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DadosDividas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('empresa', models.CharField(default='', max_length=50)),
                ('valor_divida_original', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_divida_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tipo_divida', models.CharField(default='', max_length=20)),
                ('numero_contrato', models.IntegerField(default=0)),
                ('data_divida', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='listabens',
            name='data_aquisicao',
        ),
        migrations.RemoveField(
            model_name='listabens',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='listabens',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='listabens',
            name='valor_aquisicao',
        ),
        migrations.RemoveField(
            model_name='listabens',
            name='valor_atual',
        ),
        migrations.RemoveField(
            model_name='listadividas',
            name='data_divida',
        ),
        migrations.RemoveField(
            model_name='listadividas',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='listadividas',
            name='numero_contrato',
        ),
        migrations.RemoveField(
            model_name='listadividas',
            name='tipo_divida',
        ),
        migrations.RemoveField(
            model_name='listadividas',
            name='valor_divida_atual',
        ),
        migrations.RemoveField(
            model_name='listadividas',
            name='valor_divida_original',
        ),
        migrations.AddField(
            model_name='dados',
            name='id_lista_bens',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='acessoDados.ListaBens'),
        ),
        migrations.AddField(
            model_name='dados',
            name='id_lista_dividas',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='acessoDados.ListaDividas'),
        ),
    ]
